/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    LandRegistry: {
      address: "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_approver",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "landOwnerAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "string",
              name: "userDid",
              type: "string",
            },
            {
              indexed: true,
              internalType: "string",
              name: "thramNumber",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "plotNumber",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "areaInAcre",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "areaInDecimal",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "LandRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "string",
              name: "thramNumber",
              type: "string",
            },
            {
              indexed: true,
              internalType: "string",
              name: "plotNumber",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          name: "LandVerified",
          type: "event",
        },
        {
          inputs: [],
          name: "approver",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_plotNumber",
              type: "string",
            },
          ],
          name: "getLandByPlotNumber",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          name: "getLandsByOwner",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "landOwnerAddress",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "userDid",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "thramNumber",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "plotNumber",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "location",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "areaInAcre",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "areaInDecimal",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isVerified",
                  type: "bool",
                },
              ],
              internalType: "struct LandRegistry.LandDetails[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_userDid",
              type: "string",
            },
          ],
          name: "getLandsByUserDid",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "landOwnerAddress",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "userDid",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "thramNumber",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "plotNumber",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "location",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "areaInAcre",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "areaInDecimal",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isVerified",
                  type: "bool",
                },
              ],
              internalType: "struct LandRegistry.LandDetails[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_thramNumber",
              type: "string",
            },
          ],
          name: "getPlotsByThramNumber",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "landOwnerAddress",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "userDid",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "thramNumber",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "plotNumber",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "location",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "areaInAcre",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "areaInDecimal",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "timestamp",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isVerified",
                  type: "bool",
                },
              ],
              internalType: "struct LandRegistry.LandDetails[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "landsByOwner",
          outputs: [
            {
              internalType: "address",
              name: "landOwnerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "userDid",
              type: "string",
            },
            {
              internalType: "string",
              name: "thramNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "plotNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "areaInAcre",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "areaInDecimal",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          name: "landsByPlotNumber",
          outputs: [
            {
              internalType: "address",
              name: "landOwnerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "userDid",
              type: "string",
            },
            {
              internalType: "string",
              name: "thramNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "plotNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "areaInAcre",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "areaInDecimal",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "landsByThramNumber",
          outputs: [
            {
              internalType: "address",
              name: "landOwnerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "userDid",
              type: "string",
            },
            {
              internalType: "string",
              name: "thramNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "plotNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "areaInAcre",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "areaInDecimal",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "landsByUserDid",
          outputs: [
            {
              internalType: "address",
              name: "landOwnerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "userDid",
              type: "string",
            },
            {
              internalType: "string",
              name: "thramNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "plotNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "location",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "areaInAcre",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "areaInDecimal",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isVerified",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_thramNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "_plotNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "_location",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_areaInAcre",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_areaInDecimal",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_landOwnerAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "_userDid",
              type: "string",
            },
          ],
          name: "registerLand",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_thramNumber",
              type: "string",
            },
            {
              internalType: "string",
              name: "_plotNumber",
              type: "string",
            },
          ],
          name: "verifyLand",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
